<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            [1,  'الفاتحة',       'Al-Fatihah',      7,   'makkiyah'],
            [2,  'البقرة',        'Al-Baqarah',      286, 'madaniyah'],
            [3,  'آل عمران',      "Ali 'Imran",      200, 'madaniyah'],
            [4,  'النساء',        "An-Nisa'",        176, 'madaniyah'],
            [5,  'المائدة',       "Al-Ma'idah",      120, 'madaniyah'],
            [6,  'الأنعام',       "Al-An'am",        165, 'makkiyah'],
            [7,  'الأعراف',       "Al-A'raf",        206, 'makkiyah'],
            [8,  'الأنفال',       'Al-Anfal',        75,  'madaniyah'],
            [9,  'التوبة',        'At-Taubah',       129, 'madaniyah'],
            [10, 'يونس',          'Yunus',           109, 'makkiyah'],
            [11, 'هود',           'Hud',             123, 'makkiyah'],
            [12, 'يوسف',          'Yusuf',           111, 'makkiyah'],
            [13, 'الرعد',         "Ar-Ra'd",         43,  'madaniyah'],
            [14, 'إبراهيم',       'Ibrahim',         52,  'makkiyah'],
            [15, 'الحجر',         'Al-Hijr',         99,  'makkiyah'],
            [16, 'النحل',         'An-Nahl',         128, 'makkiyah'],
            [17, 'الإسراء',       "Al-Isra'",        111, 'makkiyah'],
            [18, 'الكهف',         'Al-Kahf',         110, 'makkiyah'],
            [19, 'مريم',          'Maryam',          98,  'makkiyah'],
            [20, 'طه',            'Ta Ha',           135, 'makkiyah'],
            [21, 'الأنبياء',      "Al-Anbiya'",      112, 'makkiyah'],
            [22, 'الحج',          'Al-Hajj',         78,  'madaniyah'],
            [23, 'المؤمنون',      "Al-Mu'minun",     118, 'makkiyah'],
            [24, 'النور',         'An-Nur',          64,  'madaniyah'],
            [25, 'الفرقان',       'Al-Furqan',       77,  'makkiyah'],
            [26, 'الشعراء',       "Asy-Syu'ara'",    227, 'makkiyah'],
            [27, 'النمل',         'An-Naml',         93,  'makkiyah'],
            [28, 'القصص',         'Al-Qasas',        88,  'makkiyah'],
            [29, 'العنكبوت',      "Al-'Ankabut",     69,  'makkiyah'],
            [30, 'الروم',         'Ar-Rum',          60,  'makkiyah'],
            [31, 'لقمان',          'Luqman',          34,  'makkiyah'],
            [32, 'السجدة',         'As-Sajdah',       30,  'makkiyah'],
            [33, 'الأحزاب',        'Al-Ahzab',        73,  'madaniyah'],
            [34, 'سبأ',            "Saba'",           54,  'makkiyah'],
            [35, 'فاطر',           'Fatir',           45,  'makkiyah'],
            [36, 'يس',             'Ya Sin',          83,  'makkiyah'],
            [37, 'الصافات',        'As-Saffat',       182, 'makkiyah'],
            [38, 'ص',              'Sad',             88,  'makkiyah'],
            [39, 'الزمر',          'Az-Zumar',        75,  'makkiyah'],
            [40, 'غافر',           'Gafir',           85,  'makkiyah'],
            [41, 'فصلت',           'Fussilat',        54,  'makkiyah'],
            [42, 'الشورى',         'Asy-Syura',       53,  'makkiyah'],
            [43, 'الزخرف',         'Az-Zukhruf',      89,  'makkiyah'],
            [44, 'الدخان',         'Ad-Dukhan',       59,  'makkiyah'],
            [45, 'الجاثية',        'Al-Jasiyah',      37,  'makkiyah'],
            [46, 'الأحقاف',        'Al-Ahqaf',        35,  'makkiyah'],
            [47, 'محمد',           'Muhammad',        38,  'madaniyah'],
            [48, 'الفتح',          'Al-Fath',         29,  'madaniyah'],
            [49, 'الحجرات',        'Al-Hujurat',      18,  'madaniyah'],
            [50, 'ق',              'Qaf',             45,  'makkiyah'],
            [51, 'الذاريات',       'Az-Zariyat',      60,  'makkiyah'],
            [52, 'الطور',          'At-Tur',          49,  'makkiyah'],
            [53, 'النجم',          'An-Najm',         62,  'makkiyah'],
            [54, 'القمر',          'Al-Qamar',        55,  'makkiyah'],
            [55, 'الرحمن',         'Ar-Rahman',       78,  'madaniyah'],
            [56, 'الواقعة',        "Al-Waqi'ah",      96,  'makkiyah'],
            [57, 'الحديد',         'Al-Hadid',        29,  'madaniyah'],
            [58, 'المجادلة',       'Al-Mujadilah',    22,  'madaniyah'],
            [59, 'الحشر',          'Al-Hasyr',        24,  'madaniyah'],
            [60, 'الممتحنة',       'Al-Mumtahanah',   13,  'madaniyah'],
            [61, 'الصف',           'As-Saf',          14,  'madaniyah'],
            [62, 'الجمعة',         "Al-Jumu'ah",      11,  'madaniyah'],
            [63, 'المنافقون',      'Al-Munafiqun',    11,  'madaniyah'],
            [64, 'التغابن',        'At-Tagabun',      18,  'madaniyah'],
            [65, 'الطلاق',         'At-Talaq',        12,  'madaniyah'],
            [66, 'التحريم',        'At-Tahrim',       12,  'madaniyah'],
            [67, 'الملك',          'Al-Mulk',         30,  'makkiyah'],
            [68, 'القلم',          'Al-Qalam',        52,  'makkiyah'],
            [69, 'الحاقة',         'Al-Haqqah',       52,  'makkiyah'],
            [70, 'المعارج',        "Al-Ma'arij",      44,  'makkiyah'],
            [71, 'نوح',            'Nuh',             28,  'makkiyah'],
            [72, 'الجن',           'Al-Jinn',         28,  'makkiyah'],
            [73, 'المزمل',         'Al-Muzzammil',    20,  'makkiyah'],
            [74, 'المدثر',         'Al-Muddassir',    56,  'makkiyah'],
            [75, 'القيامة',        'Al-Qiyamah',      40,  'makkiyah'],
            [76, 'الإنسان',        'Al-Insan',        31,  'madaniyah'],
            [77, 'المرسلات',       'Al-Mursalat',     50,  'makkiyah'],
            [78, 'النبأ',          "An-Naba'",        40,  'makkiyah'],
            [79, 'النازعات',       "An-Nazi'at",      46,  'makkiyah'],
            [80, 'عبس',            "'Abasa",          42,  'makkiyah'],
            [81, 'التكوير',        'At-Takwir',       29,  'makkiyah'],
            [82, 'الانفطار',       'Al-Infitar',      19,  'makkiyah'],
            [83, 'المطففين',       'Al-Mutaffifin',   36,  'makkiyah'],
            [84, 'الانشقاق',       'Al-Insyiqaq',     25,  'makkiyah'],
            [85, 'البروج',         'Al-Buruj',        22,  'makkiyah'],
            [86, 'الطارق',         'At-Tariq',        17,  'makkiyah'],
            [87, 'الأعلى',         "Al-A'la",         19,  'makkiyah'],
            [88, 'الغاشية',        'Al-Gasyiyah',     26,  'makkiyah'],
            [89, 'الفجر',          'Al-Fajr',         30,  'makkiyah'],
            [90, 'البلد',          'Al-Balad',        20,  'makkiyah'],
            [91,  'الشمس',          'Asy-Syams',       15,  'makkiyah'],
            [92,  'الليل',          'Al-Lail',         21,  'makkiyah'],
            [93,  'الضحى',          'Ad-Duha',         11,  'makkiyah'],
            [94,  'الشرح',          'Asy-Syarh',       8,   'makkiyah'],
            [95,  'التين',          'At-Tin',          8,   'makkiyah'],
            [96,  'العلق',          "Al-'Alaq",        19,  'makkiyah'],
            [97,  'القدر',          'Al-Qadr',         5,   'makkiyah'],
            [98,  'البينة',         'Al-Bayyinah',     8,   'madaniyah'],
            [99,  'الزلزلة',        'Az-Zalzalah',     8,   'madaniyah'],
            [100, 'العاديات',       "Al-'Adiyat",      11,  'makkiyah'],
            [101, 'القارعة',        "Al-Qari'ah",      11,  'makkiyah'],
            [102, 'التكاثر',        'At-Takasur',      8,   'makkiyah'],
            [103, 'العصر',          "Al-'Asr",         3,   'makkiyah'],
            [104, 'الهمزة',         'Al-Humazah',      9,   'makkiyah'],
            [105, 'الفيل',          'Al-Fil',          5,   'makkiyah'],
            [106, 'قريش',           'Quraisy',         4,   'makkiyah'],
            [107, 'الماعون',        "Al-Ma'un",        7,   'makkiyah'],
            [108, 'الكوثر',         'Al-Kausar',       3,   'makkiyah'],
            [109, 'الكافرون',       'Al-Kafirun',      6,   'makkiyah'],
            [110, 'النصر',          'An-Nasr',         3,   'madaniyah'],
            [111, 'المسد',          'Al-Masad',        5,   'makkiyah'],
            [112, 'الإخلاص',        'Al-Ikhlas',       4,   'makkiyah'],
            [113, 'الفلق',          'Al-Falaq',        5,   'makkiyah'],
            [114, 'الناس',          'An-Nas',          6,   'makkiyah'],
        ];

        foreach ($surahs as [$nomor, $nama, $latin, $ayat, $jenis]) {
            DB::table('surah')->updateOrInsert(
                ['nomor_surah' => $nomor],
                [
                    'nomor_surah' => $nomor,
                    'nama_surah'  => $nama,
                    'nama_latin'  => $latin,
                    'jumlah_ayat' => $ayat,
                    'jenis'       => $jenis,
                ]
            );
        }
    }
}
